### ISSUE TITLE
Lacking usage and install instructions.

### ISSUE THREAD

**Issue by N07070** [alexadam/img-encode#1]
Hello

It seems that they are no usage and/or install instructions. Could they be added?

Thanks.

**Comment by alexadam** [comment]
Hi,  
Thanks for reporting this. I've added an usage example for the javascript version. Please let me know if there is something unclear  or if you need more info.
This is the example I've added:  

There are 2 versions: python ('v1-python' - no longer maintained) and javascript ('v2-js') This is an usage example for the javascript version, tested on Firefox 41, Ubuntu 15.10, Sonic Visualizer 2.4
1. Download as .zip or clone the repository
   1. go to the '/img-encode' folder
   2. copy 'monalisa.jpg' to the '/v2-js' folder
   3. open '/v2-js/index.html' in Firefox
   4. click on 'Load Image...' then on 'Create'
   5. After a few seconds you will be prompted to save the generated 'result.wav' (audio) file
   6. Open 'result.wav' with Sonic Visualizer then click on 'Layer -> add Spectrogram'

**Comment by N07070** [comment]
Perfect ! Thanks !
